service: full-presigned-urls-flow

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  region: us-east-1
  httpApi:
    cors: true
  environment:
    BUCKET_NAME:
      Ref: FullPresignedURLFlowBucket
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 's3:PutObject'
          Resource:
            Fn::Sub: '${FullPresignedURLFlowBucket.Arn}/*'

package:
  individually: true

build:
  esbuild:
    minify: true
    sourcemap: false

functions:
  getPresignedUrl:
    handler: src/functions/get-presigned-url.handler
    events:
      - httpApi:
          path: /
          method: POST

resources:
  Resources:
    FullPresignedURLFlowBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: full-presigned-urls-flow
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
              AllowedMethods:
                - PUT
