service: full-presigned-urls-flow

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  region: us-east-1
  httpApi:
    cors: true
  environment:
    BUCKET_NAME:
      Ref: FullPresignedURLFlowBucket
    TABLE_NAME:
      Ref: FullPresignedURLsFlowTable
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 's3:PutObject'
          Resource:
            Fn::Sub: '${FullPresignedURLFlowBucket.Arn}/*'
        - Effect: Allow
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:UpdateItem'
          Resource:
            Fn::GetAtt:
              - FullPresignedURLsFlowTable
              - Arn

package:
  individually: true

build:
  esbuild:
    minify: true
    sourcemap: false

functions:
  getPresignedUrl:
    handler: src/functions/get-presigned-url.handler
    events:
      - httpApi:
          path: /
          method: POST
  fileUploadTrigger:
    handler: src/functions/file-upload-trigger.handler
    events:
      - s3:
          bucket: !Ref FullPresignedURLFlowBucket
          event: s3:ObjectCreated:Put
          existing: true

resources:
  Resources:
    FullPresignedURLFlowBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: full-presigned-urls-flow
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
              AllowedMethods:
                - PUT
    FullPresignedURLsFlowTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: fileKey
            AttributeType: S
        KeySchema:
          - AttributeName: fileKey
            KeyType: HASH
        TableName: full_presigned_urls_flow_table
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
